### ISSUE TITLE
What is the purpose of hash_plus.k2d?

### ISSUE THREAD

**Issue by maflister** [davide92/K2Mem#2]
We store the reference database information in a read-only location. Because of this, the k2mem script fails at line 124 to write a hash_plus.k2d file to the database location. As far as I see, this file is actually empty and serves no purpose. If this is true, can we safely remove this part of code?

Thanks!

**Comment by davide92** [comment]
Hi, no because the file hash_plus.k2d is used during the classification to save the new discriminative minimizers.


You're welcome.
Thanks to you!

**Comment by maflister** [comment]
That makes sense. I ended up adding a check to see if the database directory is writable. If not, then it writes the file to the cwd.

Thanks again.
