### ISSUE TITLE
K2Mem Running Endlessly

### ISSUE THREAD

**Issue by nphage** [davide92/K2Mem#3]
I am having an issue where K2Mem runs endlessly and I never get any results. After some experimenting I found that this issue seems to be due to some relationship between individual reads and the Kraken2 index that I am using. I have been using the premade Kraken2 indexes PlusPF and PlusPF-8 available at https://benlangmead.github.io/aws-indexes/k2. Is it ok to use indexes that have been built by Kraken2 or do they need to be built with K2Mem?
Initially I was testing a fastq file with hundreds of thousands of reads and it wasn't completing the run in a reasonable time frame. I tested K2Mem with a single read and it completed fine in seconds. So I created subsets of my original fastq file and found that I could get it to run fine with hundreds of reads? However, some random sets of 100 reads would work and others would not. Eventually I was able to find a single read that was causing the run to fail. Here is the sequence for that read: CGCGTCGTGATTAGCGCCGTGGCCTGATTCATTCCCCAGCGACCAGATGATCACACTCGGGTGATTACGATCGCGCTGCACCATTCGCGTTACGCGTTCGCTCATCGCCGGTAGCCAGCGCGGATCATCGGTCAGACGATTCATTGGCACCATGCCGATCACCGACTGCCCATAGAGAGGAAAGCGGAGGCGTAGTGGA. Most of the read matches E. coli. If I cut the read down to just the first 41 bp K2Mem completes in seconds, but if it is the first 42 bp K2Mem just runs endlessly. If I use another of the premade indexes (EuPathDB48) that does not contain E. coli K2Mem completes in seconds. Any idea what might be causing this issue? Thanks.

**Comment by davide92** [comment]
Hi,
 K2Mem uses Kraken2 database, so the use of a pre-made database is not a problem.
 I have no idea what is causing the error. I try to find and fix the problem this weekend.
You're welcome

**Comment by nphage** [comment]
Ok. Thanks for looking into it. Hopefully the issue is not too hard to figure out.

**Comment by davide92** [comment]
Hello,
     The problem was in the code.
     I didn't handle a case within the classification cycle, causing the program to run indefinitely.
     Now the issue has been solved.

Thanks for letting me know about the problem.

**Comment by nphage** [comment]
Thanks. I will try out the updated version and let you know if I have any issues.
